/**
 * 功能：质量规则 DTO
 * 时间：2026-05-08
 * 作者：AxeXie
 */
package com.harnessdg.model.quality.dto;

import lombok.Data;

import java.util.Map;

@Data
public class QualityRuleDTO {

    private Long id;

    private Long entityId;

    private Long metricId;

    private String ruleType;

    private String ruleName;

    private String ruleExpression;

    private Map<String, Object> threshold;

    private String severity;

    private String status;

    private Boolean autoGenerated;

    private String scheduleCron;

    private String description;
}
