package com.harnessdg.model.quality.entity;

import com.baomidou.mybatisplus.annotation.TableField;
import com.baomidou.mybatisplus.annotation.TableName;
import com.baomidou.mybatisplus.extension.handlers.JacksonTypeHandler;
import com.harnessdg.common.base.BaseEntity;
import lombok.Data;
import lombok.EqualsAndHashCode;

import java.util.Map;

/**
 * 功能：质量规则 Entity
 * 时间：2026-05-08
 * 作者：AxeXie
 */
@Data
@EqualsAndHashCode(callSuper = true)
@TableName(value = "gov_quality_rule", autoResultMap = true)
public class QualityRule extends BaseEntity {

    private Long entityId;

    private Long metricId;

    private String ruleType;

    private String ruleName;

    private String ruleExpression;

    @TableField(typeHandler = JacksonTypeHandler.class)
    private Map<String, Object> threshold;

    private String severity;

    private String status;

    private Boolean autoGenerated;

    private String scheduleCron;

    private String description;
}
