/**
 * 功能：质量规则 Service 实现
 * 时间：2026-05-08
 * 作者：AxeXie
 */
package com.harnessdg.quality.service.impl;

import com.baomidou.mybatisplus.core.conditions.query.LambdaQueryWrapper;
import com.harnessdg.common.exception.BizException;
import com.harnessdg.common.response.ErrorCode;
import com.harnessdg.model.quality.dto.QualityRuleAutoGenerateRequest;
import com.harnessdg.model.quality.dto.QualityRuleCreateRequest;
import com.harnessdg.model.quality.dto.QualityRuleDTO;
import com.harnessdg.model.quality.entity.QualityRule;
import com.harnessdg.quality.mapper.QualityRuleMapper;
import com.harnessdg.quality.service.QualityRuleService;
import lombok.RequiredArgsConstructor;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import java.util.List;
import java.util.stream.Collectors;

@Service
@RequiredArgsConstructor
public class QualityRuleServiceImpl implements QualityRuleService {

    private final QualityRuleMapper qualityRuleMapper;

    @Override
    public List<QualityRuleDTO> listRules(Long entityId, String ruleType, String status) {
        LambdaQueryWrapper<QualityRule> wrapper = new LambdaQueryWrapper<>();
        if (entityId != null) {
            wrapper.eq(QualityRule::getEntityId, entityId);
        }
        if (ruleType != null && !ruleType.isBlank()) {
            wrapper.eq(QualityRule::getRuleType, ruleType);
        }
        if (status != null && !status.isBlank()) {
            wrapper.eq(QualityRule::getStatus, status);
        }
        wrapper.orderByDesc(QualityRule::getCreatedAt);
        return qualityRuleMapper.selectList(wrapper).stream()
                .map(this::toDTO)
                .collect(Collectors.toList());
    }

    @Override
    public QualityRuleDTO getRule(Long id) {
        QualityRule entity = qualityRuleMapper.selectById(id);
        if (entity == null) {
            throw new BizException(ErrorCode.QUALITY_RULE_NOT_FOUND);
        }
        return toDTO(entity);
    }

    @Override
    @Transactional
    public QualityRuleDTO createRule(QualityRuleCreateRequest request) {
        QualityRule entity = new QualityRule();
        entity.setEntityId(request.getEntityId());
        entity.setMetricId(request.getMetricId());
        entity.setRuleType(request.getRuleType());
        entity.setRuleName(request.getRuleName());
        entity.setRuleExpression(request.getRuleExpression());
        entity.setThreshold(request.getThreshold());
        entity.setSeverity(request.getSeverity());
        entity.setScheduleCron(request.getScheduleCron());
        entity.setDescription(request.getDescription());
        entity.setStatus("active");
        entity.setAutoGenerated(false);
        qualityRuleMapper.insert(entity);
        return toDTO(entity);
    }

    @Override
    @Transactional
    public QualityRuleDTO updateRule(Long id, QualityRuleCreateRequest request) {
        QualityRule entity = qualityRuleMapper.selectById(id);
        if (entity == null) {
            throw new BizException(ErrorCode.QUALITY_RULE_NOT_FOUND);
        }

        if (request.getEntityId() != null) entity.setEntityId(request.getEntityId());
        if (request.getMetricId() != null) entity.setMetricId(request.getMetricId());
        if (request.getRuleType() != null) entity.setRuleType(request.getRuleType());
        if (request.getRuleName() != null) entity.setRuleName(request.getRuleName());
        if (request.getRuleExpression() != null) entity.setRuleExpression(request.getRuleExpression());
        if (request.getThreshold() != null) entity.setThreshold(request.getThreshold());
        if (request.getSeverity() != null) entity.setSeverity(request.getSeverity());
        if (request.getScheduleCron() != null) entity.setScheduleCron(request.getScheduleCron());
        if (request.getDescription() != null) entity.setDescription(request.getDescription());

        qualityRuleMapper.updateById(entity);
        return toDTO(entity);
    }

    @Override
    @Transactional
    public void deleteRule(Long id) {
        QualityRule entity = qualityRuleMapper.selectById(id);
        if (entity == null) {
            throw new BizException(ErrorCode.QUALITY_RULE_NOT_FOUND);
        }
        qualityRuleMapper.deleteById(id);
    }

    @Override
    @Transactional
    public List<QualityRuleDTO> autoGenerateRules(QualityRuleAutoGenerateRequest request) {
        // TODO: 根据实体字段类型自动生成质量规则
        // 当前返回空列表，后续实现自动生成逻辑
        return List.of();
    }

    private QualityRuleDTO toDTO(QualityRule entity) {
        QualityRuleDTO dto = new QualityRuleDTO();
        dto.setId(entity.getId());
        dto.setEntityId(entity.getEntityId());
        dto.setMetricId(entity.getMetricId());
        dto.setRuleType(entity.getRuleType());
        dto.setRuleName(entity.getRuleName());
        dto.setRuleExpression(entity.getRuleExpression());
        dto.setThreshold(entity.getThreshold());
        dto.setSeverity(entity.getSeverity());
        dto.setStatus(entity.getStatus());
        dto.setAutoGenerated(entity.getAutoGenerated());
        dto.setScheduleCron(entity.getScheduleCron());
        dto.setDescription(entity.getDescription());
        return dto;
    }
}
