/**
 * 功能：质量规则服务单元测试
 * 时间：2026-05-12
 * 作者：AxeXie
 */
package com.harnessdg.quality.service;

import com.baomidou.mybatisplus.core.conditions.query.LambdaQueryWrapper;
import com.harnessdg.common.exception.BizException;
import com.harnessdg.model.ontology.entity.OntEntity;
import com.harnessdg.model.ontology.entity.OntMetric;
import com.harnessdg.model.quality.dto.QualityRuleAutoGenerateRequest;
import com.harnessdg.model.quality.dto.QualityRuleCreateRequest;
import com.harnessdg.model.quality.dto.QualityRuleDTO;
import com.harnessdg.model.quality.entity.QualityRule;
import com.harnessdg.ontology.mapper.OntEntityMapper;
import com.harnessdg.ontology.mapper.OntMetricMapper;
import com.harnessdg.quality.mapper.QualityRuleMapper;
import com.harnessdg.quality.service.impl.QualityRuleServiceImpl;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.mockito.ArgumentCaptor;
import org.mockito.InjectMocks;
import org.mockito.Mock;
import org.mockito.junit.jupiter.MockitoExtension;

import java.util.List;
import java.util.Map;

import static org.junit.jupiter.api.Assertions.*;
import static org.mockito.ArgumentMatchers.any;
import static org.mockito.Mockito.*;

@ExtendWith(MockitoExtension.class)
class QualityRuleServiceTest {

    @Mock
    private QualityRuleMapper qualityRuleMapper;

    @Mock
    private OntEntityMapper ontEntityMapper;

    @Mock
    private OntMetricMapper ontMetricMapper;

    @InjectMocks
    private QualityRuleServiceImpl qualityRuleService;

    private QualityRule sampleRule;

    @BeforeEach
    void setUp() {
        // 初始化测试质量规则
        sampleRule = new QualityRule();
        sampleRule.setId(1L);
        sampleRule.setEntityId(100L);
        sampleRule.setMetricId(null);
        sampleRule.setRuleType("not_null");
        sampleRule.setRuleName("name 非空检查");
        sampleRule.setRuleExpression("{\"field\": \"name\", \"check\": \"not_null\"}");
        sampleRule.setThreshold(null);
        sampleRule.setSeverity("warning");
        sampleRule.setStatus("active");
        sampleRule.setAutoGenerated(false);
        sampleRule.setScheduleCron("0 0 2 * * ?");
        sampleRule.setDescription("名称字段不能为空");
    }

    /**
     * 测试：创建质量规则成功
     * 验证：规则插入成功，返回 DTO 数据正确
     */
    @Test
    void testCreateRule_success() {
        // 准备请求数据
        QualityRuleCreateRequest request = new QualityRuleCreateRequest();
        request.setEntityId(100L);
        request.setMetricId(200L);
        request.setRuleType("unique");
        request.setRuleName("ID 唯一性检查");
        request.setRuleExpression("{\"field\": \"id\", \"check\": \"unique\"}");
        request.setSeverity("critical");
        request.setScheduleCron("0 0 1 * * ?");
        request.setDescription("主键唯一性校验");

        // 执行
        QualityRuleDTO result = qualityRuleService.createRule(request);

        // 验证
        assertNotNull(result);
        assertEquals(100L, result.getEntityId());
        assertEquals(200L, result.getMetricId());
        assertEquals("unique", result.getRuleType());
        assertEquals("ID 唯一性检查", result.getRuleName());
        assertEquals("critical", result.getSeverity());
        assertEquals("active", result.getStatus());
        assertFalse(result.getAutoGenerated());
        verify(qualityRuleMapper).insert(any(QualityRule.class));
    }

    /**
     * 测试：更新质量规则
     * 验证：规则更新成功，只更新非 null 字段
     */
    @Test
    void testUpdateRule() {
        // 模拟现有规则
        when(qualityRuleMapper.selectById(1L)).thenReturn(sampleRule);

        // 准备更新请求（只更新部分字段）
        QualityRuleCreateRequest request = new QualityRuleCreateRequest();
        request.setEntityId(null); // 不更新
        request.setRuleName("更新后的规则名称");
        request.setSeverity("critical");
        request.setDescription("更新后的描述");

        // 执行
        QualityRuleDTO result = qualityRuleService.updateRule(1L, request);

        // 验证
        assertNotNull(result);
        assertEquals("更新后的规则名称", result.getRuleName());
        assertEquals("critical", result.getSeverity());
        assertEquals("更新后的描述", result.getDescription());
        // 未更新的字段保持原值
        assertEquals(100L, result.getEntityId());
        assertEquals("not_null", result.getRuleType());
        verify(qualityRuleMapper).updateById(any(QualityRule.class));
    }

    /**
     * 测试：删除质量规则
     * 验证：规则删除成功
     */
    @Test
    void testDeleteRule() {
        // 模拟现有规则
        when(qualityRuleMapper.selectById(1L)).thenReturn(sampleRule);

        // 执行
        assertDoesNotThrow(() -> qualityRuleService.deleteRule(1L));

        // 验证
        verify(qualityRuleMapper).deleteById(1L);
    }

    /**
     * 测试：删除不存在的规则
     * 验证：抛出 BizException
     */
    @Test
    void testDeleteRule_notFound() {
        when(qualityRuleMapper.selectById(999L)).thenReturn(null);

        // 执行并验证异常
        assertThrows(BizException.class, () -> qualityRuleService.deleteRule(999L));
        verify(qualityRuleMapper, never()).deleteById(any(Long.class));
    }

    /**
     * 测试：获取规则详情 - 规则不存在
     * 验证：抛出 BizException (QUALITY_RULE_NOT_FOUND)
     */
    @Test
    void testGetRule_notFound() {
        when(qualityRuleMapper.selectById(999L)).thenReturn(null);

        // 执行并验证异常
        assertThrows(BizException.class, () -> qualityRuleService.getRule(999L));
    }

    /**
     * 测试：按规则类型查询
     * 验证：listRules 方法使用 ruleType 条件过滤
     */
    @Test
    void testListRules_byType() {
        // 准备多个规则
        QualityRule rule1 = new QualityRule();
        rule1.setId(1L);
        rule1.setEntityId(100L);
        rule1.setRuleType("not_null");
        rule1.setRuleName("规则1");
        rule1.setRuleExpression("{}");
        rule1.setStatus("active");

        QualityRule rule2 = new QualityRule();
        rule2.setId(2L);
        rule2.setEntityId(100L);
        rule2.setRuleType("not_null");
        rule2.setRuleName("规则2");
        rule2.setRuleExpression("{}");
        rule2.setStatus("active");

        when(qualityRuleMapper.selectList(any(LambdaQueryWrapper.class)))
                .thenReturn(List.of(rule1, rule2));

        // 执行
        List<QualityRuleDTO> result = qualityRuleService.listRules(null, "not_null", null);

        // 验证
        assertEquals(2, result.size());
        assertEquals("not_null", result.get(0).getRuleType());
        assertEquals("not_null", result.get(1).getRuleType());
    }

    /**
     * 测试：按目标实体查询
     * 验证：listRules 方法使用 entityId 条件过滤
     */
    @Test
    void testListRules_byEntityId() {
        QualityRule rule = new QualityRule();
        rule.setId(1L);
        rule.setEntityId(100L);
        rule.setRuleType("range");
        rule.setRuleName("数值范围检查");
        rule.setRuleExpression("{}");
        rule.setStatus("active");

        when(qualityRuleMapper.selectList(any(LambdaQueryWrapper.class)))
                .thenReturn(List.of(rule));

        // 执行
        List<QualityRuleDTO> result = qualityRuleService.listRules(100L, null, null);

        // 验证
        assertEquals(1, result.size());
        assertEquals(100L, result.get(0).getEntityId());
    }

    /**
     * 测试：按状态查询
     * 验证：listRules 方法使用 status 条件过滤
     */
    @Test
    void testListRules_byStatus() {
        QualityRule rule = new QualityRule();
        rule.setId(1L);
        rule.setEntityId(100L);
        rule.setRuleType("unique");
        rule.setRuleName("唯一性检查");
        rule.setRuleExpression("{}");
        rule.setStatus("disabled");

        when(qualityRuleMapper.selectList(any(LambdaQueryWrapper.class)))
                .thenReturn(List.of(rule));

        // 执行
        List<QualityRuleDTO> result = qualityRuleService.listRules(null, null, "disabled");

        // 验证
        assertEquals(1, result.size());
        assertEquals("disabled", result.get(0).getStatus());
    }

    /**
     * 测试：自动生成规则 - 从实体字段生成
     * 验证：根据实体标签中的 fields 元数据自动生成规则
     */
    @Test
    void testAutoGenerateRules_fromEntity() {
        // 准备请求
        QualityRuleAutoGenerateRequest request = new QualityRuleAutoGenerateRequest();
        request.setEntityId(100L);

        // 模拟实体数据（带有字段元数据）
        OntEntity entity = new OntEntity();
        entity.setId(100L);
        entity.setName("test_table");
        entity.setTags(Map.of("fields", List.of(
                Map.of("name", "id", "type", "bigint", "is_primary_key", true, "not_null", true),
                Map.of("name", "name", "type", "string", "not_null", true),
                Map.of("name", "amount", "type", "decimal"),
                Map.of("name", "create_date", "type", "date"),
                Map.of("name", "price", "type", "float", "not_null", true)
        )));

        when(ontEntityMapper.selectById(100L)).thenReturn(entity);

        // 执行
        List<QualityRuleDTO> result = qualityRuleService.autoGenerateRules(request);

        // 验证生成的规则
        assertNotNull(result);
        // id 字段：主键 -> unique + not_null (2条)
        // name 字段：not_null (1条)
        // amount 字段：decimal -> range + fluctuation (2条)
        // create_date 字段：date -> range (1条)
        // price 字段：float + not_null + contains "price" -> range + fluctuation + not_null (3条)
        // 总共应该是 9 条规则
        assertTrue(result.size() >= 5, "Should generate at least 5 rules from test data");

        // 验证包含 unique 类型规则
        boolean hasUnique = result.stream().anyMatch(r -> "unique".equals(r.getRuleType()));
        assertTrue(hasUnique, "Should have unique rule for primary key");

        // 验证包含 not_null 类型规则
        boolean hasNotNull = result.stream().anyMatch(r -> "not_null".equals(r.getRuleType()));
        assertTrue(hasNotNull, "Should have not_null rules");

        // 验证生成的规则标记为自动生成
        boolean allAutoGenerated = result.stream().allMatch(QualityRuleDTO::getAutoGenerated);
        assertTrue(allAutoGenerated, "All auto-generated rules should have autoGenerated=true");

        // 验证规则被保存到数据库
        verify(qualityRuleMapper).insert(any(List.class));
    }

    /**
     * 测试：自动生成规则 - 从指标字段生成
     * 验证：根据指标标签中的 fields 元数据自动生成规则
     */
    @Test
    void testAutoGenerateRules_fromMetric() {
        // 准备请求
        QualityRuleAutoGenerateRequest request = new QualityRuleAutoGenerateRequest();
        request.setMetricId(200L);

        // 模拟指标数据
        OntMetric metric = new OntMetric();
        metric.setId(200L);
        metric.setEntityId(100L);
        metric.setName("test_metric");
        metric.setTags(Map.of("fields", List.of(
                Map.of("name", "value", "type", "int", "not_null", true),
                Map.of("name", "cost", "type", "decimal")
        )));

        when(ontMetricMapper.selectById(200L)).thenReturn(metric);

        // 执行
        List<QualityRuleDTO> result = qualityRuleService.autoGenerateRules(request);

        // 验证
        assertNotNull(result);
        assertTrue(result.size() >= 3, "Should generate rules from metric fields");

        // 验证规则关联到正确的 metricId 和 entityId
        boolean correctMetricId = result.stream().allMatch(r -> r.getMetricId() != null && r.getMetricId().equals(200L));
        assertTrue(correctMetricId, "Generated rules should reference the metricId");

        verify(qualityRuleMapper).insert(any(List.class));
    }

    /**
     * 测试：自动生成规则 - 实体和指标都不存在
     * 验证：返回空列表，不执行插入
     */
    @Test
    void testAutoGenerateRules_noData() {
        QualityRuleAutoGenerateRequest request = new QualityRuleAutoGenerateRequest();
        request.setEntityId(999L);
        request.setMetricId(999L);

        when(ontEntityMapper.selectById(999L)).thenReturn(null);
        when(ontMetricMapper.selectById(999L)).thenReturn(null);

        // 执行
        List<QualityRuleDTO> result = qualityRuleService.autoGenerateRules(request);

        // 验证
        assertTrue(result.isEmpty());
        verify(qualityRuleMapper, never()).insert(any());
    }

    /**
     * 测试：自动生成规则 - 实体没有 tags
     * 验证：返回空列表
     */
    @Test
    void testAutoGenerateRules_entityNoTags() {
        QualityRuleAutoGenerateRequest request = new QualityRuleAutoGenerateRequest();
        request.setEntityId(100L);

        OntEntity entity = new OntEntity();
        entity.setId(100L);
        entity.setName("test_table");
        entity.setTags(null); // 没有标签

        when(ontEntityMapper.selectById(100L)).thenReturn(entity);

        // 执行
        List<QualityRuleDTO> result = qualityRuleService.autoGenerateRules(request);

        // 验证
        assertTrue(result.isEmpty());
    }

    /**
     * 测试：自动生成规则 - 实体 tags 没有 fields
     * 验证：返回空列表
     */
    @Test
    void testAutoGenerateRules_noFieldsInTags() {
        QualityRuleAutoGenerateRequest request = new QualityRuleAutoGenerateRequest();
        request.setEntityId(100L);

        OntEntity entity = new OntEntity();
        entity.setId(100L);
        entity.setName("test_table");
        entity.setTags(Map.of("description", "No fields here")); // 没有 fields 键

        when(ontEntityMapper.selectById(100L)).thenReturn(entity);

        // 执行
        List<QualityRuleDTO> result = qualityRuleService.autoGenerateRules(request);

        // 验证
        assertTrue(result.isEmpty());
    }
}
